apiVersion: v1
kind: Service
metadata:
  name: fint-core-exporter
  annotations: {service.beta.kubernetes.io/azure-load-balancer-internal: 'true'}
spec:
  selector:
    app: fint-core-exporter
  type: LoadBalancer
  ports:
    - {name: '8080', port: 8080}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-core-exporter
spec:
  selector:
    matchLabels:
      app: fint-core-exporter
  template:
    metadata:
      labels:
        app: fint-core-exporter
    spec:
      serviceAccountName: fint-core-exporter
      containers:
        - name: fint-core-exporter
          image: fintlabsacr.azurecr.io/fint-core-exporter:build.${BUILD_NUMBER}_${GIT_COMMIT}
          env:
            - { name: kubernetes.client, value: in-cluster }
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 5
