fint:
  poll:
    initial-delay: 10000
    fixed-delay: 300000
  components:
    - administrasjon-fullmakt
    - administrasjon-kodeverk
    - administrasjon-organisasjon
    - administrasjon-personal
    - arkiv-kodeverk
    - arkiv-kulturminnevern
    - arkiv-noark
    - arkiv-personal
    - felles-kodeverk
    - okonomi-faktura
    - okonomi-kodeverk
    - utdanning-elev
    - utdanning-kodeverk
    - utdanning-timeplan
    - utdanning-utdanningsprogram
    - utdanning-vurdering

management:
  endpoints:
    web:
      exposure:
        include: "info, health, metrics, prometheus"
