name: Deploy
on:
  push:
    branches:
      - main

env:
  REGISTRY_NAME: fintlabsacr
  CLUSTER_NAME: aks-beta-fint-2021-11-23
  CLUSTER_RESOURCE_GROUP: rg-aks-beta
  NAMESPACE: default
  APP_NAME: fint-core-explorer

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository 
        uses: actions/checkout@main

      - name: Connect to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Container build and push to a Azure Container Registry (ACR)
        run: |
          docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Set the target Azure Kubernetes Service (AKS) cluster.
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AKS_BETA_FINT_GITHUB }}'
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
          images: |
            ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
          namespace: ${{ env.NAMESPACE }}